### ISSUE TITLE
SyntaxError: appears and does not work properly.

### ISSUE THREAD

**Issue by gawasa29** [ChFlick/prettier-plugin-firestore-rules#11]
I get the following error code and it does not work properly.

["ERROR" - 11:15:39] Error formatting document.
["ERROR" - 11:15:39] Expected "allow", "match", comment, or whitespace but "f" found.
SyntaxError: Expected "allow", "match", comment, or whitespace but "f" found.
	at peg$buildStructuredError (/Users/sagawayuusei/work/gawasa/node_modules/prettier-plugin-firestore-rules/out/parser/parser.js:210:16)
	at Object.peg$parse [as parse] (/Users/sagawayuusei/work/gawasa/node_modules/prettier-plugin-firestore-rules/out/parser/parser.js:3659:15)
	at Object.parse (/Users/sagawayuusei/work/gawasa/node_modules/prettier/index.js:7515:23)
	at coreFormat (/Users/sagawayuusei/work/gawasa/node_modules/prettier/index.js:8829:18)
	at formatWithCursor2 (/Users/sagawayuusei/work/gawasa/node_modules/prettier/index.js:9021:18)
	at /Users/sagawayuusei/work/gawasa/node_modules/prettier/index.js:38183:12
	at Object.format (/Users/sagawayuusei/work/gawasa/node_modules/prettier/index.js:38197:12)
	at t.default.format (/Users/sagawayuusei/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:14756)
	at async t.default.provideEdits (/Users/sagawayuusei/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:11429)
	at async forceFormatDocument (/Users/sagawayuusei/.vscode/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:8922)
	at async m.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:125789)

**Comment by niklasravnsborg** [comment]
I have the same problem...
